INSERT IGNORE INTO ISHotelCampus.camera (id, costo, immagine, is_deleted, numero_max_ospiti, quadratura, tipo, numero) VALUES (1,150, 'Images/Demo/Camere/101.JPEG', false, 3, 40, 'STANDARD', 101);
INSERT IGNORE INTO ISHotelCampus.camera (id, costo, immagine, is_deleted, numero_max_ospiti, quadratura, tipo, numero) VALUES (2,130, 'Images/Demo/Camere/102.JPEG', false, 2, 60, 'DELUXE', 102);
INSERT IGNORE INTO ISHotelCampus.camera (id, costo, immagine, is_deleted, numero_max_ospiti, quadratura, tipo, numero) VALUES (3,320, 'Images/Demo/Camere/103.JPEG', false, 4, 120, 'EXCLUSIVE', 103);
INSERT IGNORE INTO ISHotelCampus.camera (id, costo, immagine, is_deleted, numero_max_ospiti, quadratura, tipo, numero) VALUES (4,250, 'Images/Demo/Camere/104.JPEG', false, 2, 100, 'LUXURY', 104);
INSERT IGNORE INTO ISHotelCampus.camera (id, costo, immagine, is_deleted, numero_max_ospiti, quadratura, tipo, numero) VALUES (5,110, 'Images/Demo/Camere/105.JPEG', false, 2, 45, 'STANDARD', 105);
INSERT IGNORE INTO ISHotelCampus.camera (id, costo, immagine, is_deleted, numero_max_ospiti, quadratura, tipo, numero) VALUES (6,370, 'Images/Demo/Camere/106.JPEG', false, 3, 90, 'EXCLUSIVE', 106);
INSERT IGNORE INTO ISHotelCampus.camera (id, costo, immagine, is_deleted, numero_max_ospiti, quadratura, tipo, numero) VALUES (7,140, 'Images/Demo/Camere/107.JPEG', true, 2, 70, 'DELUXE', 107);
INSERT IGNORE INTO ISHotelCampus.servizio (id, nome, descrizione, costo, immagine, is_deleted) VALUES (1,'Colazione', 'Colazione a buffet', 10, 'Images/Demo/Servizi/colazione1.jpg', false);
INSERT IGNORE INTO ISHotelCampus.servizio (id, nome, descrizione, costo, immagine, is_deleted) VALUES (2,'Ristorante', 'Ristorante con cucina tipica', 30, 'Images/Demo/Servizi/ristorante1.jpg', false);
INSERT IGNORE INTO ISHotelCampus.servizio (id, nome, descrizione, costo, immagine, is_deleted) VALUES (3,'Piscina', 'Piscina coperta', 20, 'Images/Demo/Servizi/piscinaInterna1.jpg', false);
INSERT IGNORE INTO ISHotelCampus.servizio (id, nome, descrizione, costo, immagine, is_deleted) VALUES (4,'Spa', 'Spa con sauna e bagno turco', 40, 'Images/Demo/Servizi/spa1.jpg', false);
